# Make docker container.
image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 6080

tasks:
  - init: make init
    command: make run

# Gitpod requires Vscode SpringBoot plugin.
vscode:
  extensions:
    - pinage404.rust-extension-pack
    - matklad.rust-analyzer
