[package]
name = "gui_test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio= "0.14.8"
chrono = "0.4"

[dependencies.gtk]
version = "0.14.3"
features = ["v3_24"] 